# Generated by Django 3.0.11 on 2020-11-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCatagoryModel',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('Category_image', models.ImageField(blank=True, null=True, upload_to='media/product_category')),
                ('Category_desc', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddProductModell',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='media/add_product')),
                ('product_origonal_price', models.CharField(max_length=20)),
                ('product_discounted_price', models.CharField(max_length=20)),
                ('product_description', models.TextField(max_length=200)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.AddCatagoryModel')),
            ],
        ),
    ]
