# Generated by Django 3.0.11 on 2020-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcatagorymodel',
            name='Category_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_category'),
        ),
        migrations.AlterField(
            model_name='addproductmodell',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='add_product'),
        ),
    ]
